name: core
description: "Core module for the application."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.2
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
