name: invoices
description: "E-invoices"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.2
  shimmer: ^3.0.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6
  build_runner: ^2.4.13
  core:
    path: ../core
  home:
    path: ../features/feature_home

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
